export const coursesArr = [
  {
    id: 1,
    title: "React Basics",
    progress: 70,
    lecturesCompleted: 7,
    totalLectures: 10,
    status: "in-progress",
    lectures: [
      {
        id: 1,
        title: "Introduction to React",
        videoUrl: "https://youtu.be/ihRRf3EjTV8?si=xAA8MIwDrtVe1L-b",
        description: "Overview of React and its core concepts.",
        duration: "12:30",
        isCompleted: false,
      },
      {
        id: 2,
        title: "1 JSX and Rendering",
        videoUrl: "https://youtu.be/T9DTxrQ1BU0?si=vRRrUR23Jc65gcYq",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 3,
        title: "2 JSX and Rendering",
        videoUrl: "https://youtu.be/xa2TMZCy83g?si=Sh1Rfr77kPbMAVtz",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 4,
        title: "3 JSX and Rendering",
        videoUrl: "https://youtu.be/UYLS4yR9rA4?si=YBh9DewiueQ2Hkvt",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
    ],
  },
  {
    id: 2,
    title: "Advanced JavaScript",
    progress: 100,
    lecturesCompleted: 12,
    totalLectures: 12,
    status: "completed",
    lectures: [
      {
        id: 1,
        title: "Introduction to React",
        videoUrl: "https://youtu.be/ihRRf3EjTV8?si=xAA8MIwDrtVe1L-b",
        description: "Overview of React and its core concepts.",
        duration: "12:30",
        isCompleted: false,
      },
      {
        id: 2,
        title: "1 JSX and Rendering",
        videoUrl: "https://youtu.be/T9DTxrQ1BU0?si=vRRrUR23Jc65gcYq",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 3,
        title: "2 JSX and Rendering",
        videoUrl: "https://youtu.be/xa2TMZCy83g?si=Sh1Rfr77kPbMAVtz",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 4,
        title: "3 JSX and Rendering",
        videoUrl: "https://youtu.be/UYLS4yR9rA4?si=YBh9DewiueQ2Hkvt",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
    ],
  },
  {
    id: 3,
    title: "Advanced JavaScript",
    progress: 100,
    lecturesCompleted: 12,
    totalLectures: 12,
    status: "completed",
    lectures: [
      {
        id: 1,
        title: "Introduction to React",
        videoUrl: "https://youtu.be/ihRRf3EjTV8?si=xAA8MIwDrtVe1L-b",
        description: "Overview of React and its core concepts.",
        duration: "12:30",
        isCompleted: false,
      },
      {
        id: 2,
        title: "1 JSX and Rendering",
        videoUrl: "https://youtu.be/T9DTxrQ1BU0?si=vRRrUR23Jc65gcYq",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 3,
        title: "2 JSX and Rendering",
        videoUrl: "https://youtu.be/xa2TMZCy83g?si=Sh1Rfr77kPbMAVtz",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 4,
        title: "3 JSX and Rendering",
        videoUrl: "https://youtu.be/UYLS4yR9rA4?si=YBh9DewiueQ2Hkvt",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
    ],
  },
  {
    id: 4,
    title: "Advanced JavaScript",
    progress: 100,
    lecturesCompleted: 12,
    totalLectures: 12,
    status: "completed",
    lectures: [
      {
        id: 1,
        title: "Introduction to React",
        videoUrl: "https://youtu.be/ihRRf3EjTV8?si=xAA8MIwDrtVe1L-b",
        description: "Overview of React and its core concepts.",
        duration: "12:30",
        isCompleted: false,
      },
      {
        id: 2,
        title: "1 JSX and Rendering",
        videoUrl: "https://youtu.be/T9DTxrQ1BU0?si=vRRrUR23Jc65gcYq",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 3,
        title: "2 JSX and Rendering",
        videoUrl: "https://youtu.be/xa2TMZCy83g?si=Sh1Rfr77kPbMAVtz",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 4,
        title: "3 JSX and Rendering",
        videoUrl: "https://youtu.be/UYLS4yR9rA4?si=YBh9DewiueQ2Hkvt",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
    ],
  },
  {
    id: 5,
    title: "Advanced JavaScript",
    progress: 100,
    lecturesCompleted: 12,
    totalLectures: 12,
    status: "completed",
    lectures: [
      {
        id: 1,
        title: "Introduction to React",
        videoUrl: "https://youtu.be/ihRRf3EjTV8?si=xAA8MIwDrtVe1L-b",
        description: "Overview of React and its core concepts.",
        duration: "12:30",
        isCompleted: false,
      },
      {
        id: 2,
        title: "1 JSX and Rendering",
        videoUrl: "https://youtu.be/T9DTxrQ1BU0?si=vRRrUR23Jc65gcYq",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 3,
        title: "2 JSX and Rendering",
        videoUrl: "https://youtu.be/xa2TMZCy83g?si=Sh1Rfr77kPbMAVtz",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
      {
        id: 4,
        title: "3 JSX and Rendering",
        videoUrl: "https://youtu.be/UYLS4yR9rA4?si=YBh9DewiueQ2Hkvt",
        description: "Learn how JSX works in React.",
        duration: "15:45",
        isCompleted: false,
      },
    ],
  },
];
